name: Deploy

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Create artifacts
        run: |
          mkdir -p artifacts
          cp -r dist package.json README.md artifacts/
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: thinking-tool-server
          path: artifacts/
