name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
        
      - name: Create release archive
        run: |
          mkdir -p release
          cp -r dist package.json README.md release/
          cd release
          zip -r ../thinking-tool-server.zip .
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: thinking-tool-server.zip
          generate_release_notes: true
